### PR TITLE
map SQL dates and times to DateTime

### LINKED ISSUE #12: timestamp field mapping
Would it be possible for timestamp field to be mapped to  `DateTime` in `typedAssoc` method

### PR DESCRIPTION
**Pull request by fsw**
I have tested this just for my simple use case.
@zim32 I can add some more tests for column types in this PR if general approach in this change is OK.
This change is not backward compatible (**typedAssoc** will return different types)
fixes #12

### CODE REVIEW

**Comment by zim32** [comment]
Hi fsw. ThI think because this library is still not in stable semver we can just bump minor version and write changelog.

I will check your PR in a few days

**Comment by fsw** [comment]
Yes, I guess minor bump would be OK.

I am not sure what to do with sql TIME type, but I guess this one should be passed as String and not converted to DateTime. I will fix this and add some tests.

**Comment by zim32** [comment]
Yes, TIME should be just String

**Comment by fsw** [comment]
added some changes:

* map TIME to string
* map YEAR to int by default (It should fit into integer size)
* removed test.dart (guess it is unused)
* refactored tests so socket and TCP connection can be tested using same code base.
* added test for default types mapping behavior.

Few things I noticed while adding types mapping test:

* query that returns spatial type is throwing: "FormatException: Unexpected extension byte"  I guess this is not yet implemented. I left it commented out and marked with TODO in test code.
* Types that would not fit into INT (Like BIT, DECIMAL etc) are mapped to String. I guess this is OK if it will be reliable but this creates weird behaviors (like MAX(col) returns int but SUM(col) returns String). Maybe we can consider mapping those types to BigInt?

**Comment by zim32** [comment]
I think if we convert year to INT now, users will expect that numbers will be converted to numbers or at least to BigInt. So yeah it is logical to convert them to BigInt.

**Comment by zim32** [comment]
I am merging this PR, but we need to implement BigInt mapping to be consistent.

**Comment by zim32** [comment]
You changed something in the tests, so now they are not working.

dart test test/mysql_client.dart

```
00:00 +0 -1: loading test/mysql_client.dart [E]                                                                                                                           
  Failed to load "test/mysql_client.dart":
  /tmp/dart_test.TYGLEF/test.dart:9:42: Error: Undefined name 'main'.
        internalBootstrapVmTest(() => test.main, sendPort);
                                           ^^^^
00:00 +0 -1: Some tests failed.  
```

**Comment by zim32** [comment]
Ah I see. You refactor and move it to separate files for TCP and Unix socket tests. Ok

**Comment by fsw** [comment]
@zim32 yes,

Maybe the file "test/mysql_client.dart" should be moved to "test/lib/mysql_client.dart" or something like this to make it more clear.

And yes the BigInt change can be separate PR.

thanks.

**Pull request merged**
